name: Docker
on: [push, pull_request]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: docker build .
        run: docker build .
