name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [dmd-latest, dmd-2.088.0]

    name: Dub - ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: apt-get install -y libsqlite3-dev
        if: startsWith( matrix.os, 'ubuntu-' )
        run: sudo apt-get install -y libsqlite3-dev

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v0.3.0
        with:
          compiler: ${{ matrix.compiler }}

      - name: dub -q test
        run: dub -q test
